## Difficult genes {#difficult_genes}


```{r DG, eval = F}
source("codes/google_difficult_genes_functions.R")

for (dataset in datasets)
{
  res.data <- list()
  groups <- unlist(read.table(file = paste0('data/', dataset, '.csv')))
  counts <- NULL
  for (map in maper)
  {
    cc <- readRDS(file = paste0("data/", dataset, "_", map, ".rds"))
    counts <- cbind(counts, cc)
  }
  res.data[["edgeR"]] <- dg.seeker5(counts, n.mapper = length(maper), exp.design = groups, method = "edgeR")
  res.data[["DESeq"]] <- dg.seeker5(counts, n.mapper = length(maper), exp.design = groups, method = "DESeq")
  res.data[["limma1"]] <- dg.seeker5(counts, n.mapper = length(maper), exp.design = groups, method = "limma1")
  res.data[["limma2"]] <- dg.seeker5(counts, n.mapper = length(maper), exp.design = groups, method = "limma2")
  saveRDS(res.data, file = paste0("results/difficult_genes_filtered_", dataset, ".rds"))
}

```

```{r data2plots-DG}
comp.mappers <- combn(maper, length(maper))
data.plot <- list()
method <- c("edgeR", "DESeq", "limma1", "limma2")

for (dataset in datasets)
{
  counts <- NULL
  for (j in 1:length(maper))
  {
    cc <- readRDS(file = paste0("data/", dataset, "_", comp.mappers[j, 1], ".rds"))
    colnames(cc) <- paste0("c",1:ncol(cc),".", comp.mappers[j, 1])
    counts <- cbind(counts, cc)
  }
  dg <- readRDS(paste0("results/difficult_genes_", dataset, ".rds"))
    
  for (met in method)
  {
    a <- data.frame(dg[[met]]$stats)
    a <- a[which(a$status.group == "Sig" & a$status.mappers == "Sig"),]
    a$ind <- a$pval.gr+a$pval.map
    a <- a[order(a$pval.map, a$pval.gr), ]
    joint.names <- match(rownames(a), rownames(cc))
    
    
    for (j in 1:length(maper))
    {
      
      if(nrow(a) > 0)
      {  
        
        data.plot[[dataset]][[met]][[comp.mappers[j,1] ]] <- counts[joint.names[1:5], (ncol(cc)*(j-1)+1):(ncol(cc)*j)]
        colnames(data.plot[[dataset]][[met]][[comp.mappers[j, 1] ]]) <- 1:ncol(cc)
      } else {
        data.plot[[dataset]][[met]][[comp.mappers[j,1] ]] <- NULL
      }
    }
  }  
}

res <- melt(data.plot)

colnames(res) <- c("Var1", "Var2", "value", "L3", "L2", "L1")

data1 <- res %>% filter(L2 == "edgeR")
data1$L1[which(data1$L1 == "dataset4")] <- "22260"
data1$L1[which(data1$L1 == "dataset5")] <- "50760"
data1$L1[which(data1$L1 == "dataset6")] <- "87340"
data1$L1[which(data1$L1 == "dataset7")] <- "42146"
data1$L1[which(data1$L1 == "dataset8")] <- "41364"
```


```{r, eval=F}
data1 %>% 
  group_by(L1) %>% 
  distinct(Var1, .keep_all = TRUE) %>% 
  filter(L1 %in% c("22260", "50760", "87340")) %>% 
  select(dataset = L1, geny = Var1) -> do.gviz
  
# saveRDS(do.gviz, file = "results/gviz_data_4-6.rds")
```


```{r plots-DG, echo=F, fig.height=16, fig.width=12}
p <- ggplot(data1) + geom_line(size = .7, 
            aes(x = Var2, y = value, group = L3, colour = L3)) +
  facet_wrap(L1~Var1, scales = "free", ncol=5) + theme_bw() +
  scale_colour_manual(values = c("#5A9AC7","#6CBB85","#E56865")) +
  scale_x_continuous(labels = function(x) round(x), breaks = function(x) pretty(x, n = 5)) +
  ylab("Counts") + xlab("Sample no") + 
  theme(legend.position = "bottom", legend.title=element_blank(),
        text = element_text(size = 10), strip.text = element_text(size = 12)) 
print(p)
ggsave("results/dg-counts.png", width = 10, height = 12, dpi = 300)

```
