--- 
title: "Odp na recenzje"
author:
- Alicja Szabelska-Beręsewicz
- Joanna Zyprych-Walczak
- Idzi Siatkowski
- Michał Okoniewski
output: html_document
---

```{r setup1, include=FALSE}
library(knitr)
library(xtable)
library(Cairo)
options(xtable.comment = FALSE)
opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE,  tidy.opts = list(width.cutoff=37), tidy=TRUE)
opts_knit$set(root.dir = "../")
opts_chunk$set(cache = F)
```

## Odpowiedzi dla recenzenta nr 2 linijki 42


```{r pakiety+ustawienia, message=FALSE, warning=FALSE, echo = F}
require(graphics); 
require(grDevices)
library(ggplot2)
library(reshape2)
library(grid)
library(knitr)
library(dplyr)
```


### Barplots

```{r}
nazwy <- dir("data/", pattern = "dataset")
nazwy <- nazwy[grep(nazwy, pattern = "Rdata")]
nazwy <- gsub(nazwy, pattern = ".Rdata", replacement = "")
datasets <- strsplit(nazwy, "_")
maper <- unique(sapply(datasets, "[[", 2))
datasets <- unique(sapply(datasets, "[[", 1))

```


```{r barploty, message=FALSE, warning=FALSE, echo = F, fig.width = 10, fig.height = 7}
library(edgeR)

res <- list()

for (dataset in datasets)
{
  dane <- matrix(,length(maper),6)
  colnames(dane) <- c('>5000','1000-5000', '500-1000', '100-500', '10-100', '<10')
  rownames(dane) <- maper
  for (map in maper)
  {
    load(file = paste0("data/", dataset, "_", map, ".RData"))
    isexpr <- rowSums(cpm(cc) > 5) >= 2
    dane1 <- cc[isexpr,]
    srednie <- rowMeans(dane1)
    dane[which(maper == map),6] <- length(which(srednie < 10))
    dane[which(maper == map),5] <- length(which(srednie >= 10 & srednie < 100))
    dane[which(maper == map),4] <- length(which(srednie >= 100 & srednie < 500))
    dane[which(maper == map),3] <- length(which(srednie >= 500 & srednie < 1000))
    dane[which(maper == map),2] <- length(which(srednie >= 1000 & srednie < 5000))
    dane[which(maper == map),1] <- length(which(srednie >= 5000))
  }
  res[[dataset]] <- dane
}

res<-melt(res)
colnames(res) <- c("maper", "abundance", "value", "dataset")
res$dataset[which(res$dataset == "dataset4")] <- "GSE22260"
res$dataset[which(res$dataset == "dataset5")] <- "GSE50760"
res$dataset[which(res$dataset == "dataset6")] <- "GSE87340"
res$dataset[which(res$dataset == "dataset7")] <- "GSE42146"
res$dataset[which(res$dataset == "dataset8")] <- "GSE41364"
res$abundance <- factor(res$abundance, levels=rev(levels(res$abundance)))

res1 <- list()
for(dataset in datasets)
{
  load(file = paste0("results/difficult_genes_", dataset, ".RData"))
  dziwne <- rownames(res.dane$edgeR$stats)[which(res.dane$edgeR$stats$status.group == 'Sig' & res.dane$edgeR$stats$status.mappers == 'Sig')]
  for (map in maper)
  {  
    load(file = paste0("data/", dataset, "_", map, ".RData"))
    isexpr <- rowSums(cpm(cc) > 5) >= 2
    dane1 <- cc[isexpr,]
    dane2 <- dane1[-which(rownames(dane1) %in% dziwne), ]
    srednie <- rowMeans(dane2)
    dane[which(maper == map),6] <- length(which(srednie < 10))
    dane[which(maper == map),5] <- length(which(srednie >= 10 & srednie < 100))
    dane[which(maper == map),4] <- length(which(srednie >= 100 & srednie < 500))
    dane[which(maper == map),3] <- length(which(srednie >= 500 & srednie < 1000))
    dane[which(maper == map),2] <- length(which(srednie >= 1000 & srednie < 5000))
    dane[which(maper == map),1] <- length(which(srednie >= 5000))
  }
  res1[[dataset]] <- dane
}

res1 <- melt(res1)
colnames(res1) <- c("maper", "abundance", "value", "dataset")
res1$dataset[which(res1$dataset == "dataset4")] <- "GSE22260"
res1$dataset[which(res1$dataset == "dataset5")] <- "GSE50760"
res1$dataset[which(res1$dataset == "dataset6")] <- "GSE87340"
res1$dataset[which(res1$dataset == "dataset7")] <- "GSE42146"
res1$dataset[which(res1$dataset == "dataset8")] <- "GSE41364"
res1$abundance <- factor(res1$abundance, levels=rev(levels(res1$abundance)))
```

```{r}
res$difficult <- "with DG"
res1$difficult <- "without DG"

res2 <- rbind(res, res1)

p <- ggplot(res2, aes(x=maper, y= value, fill = abundance, order= T), stat = "identity") +
  geom_bar(stat = "identity") +
  xlab('Methods')+ylab("No of genes") +
  facet_grid(dataset~difficult) +
  scale_fill_brewer(palette='Greens',name='Abundance\nof genes') +
  theme_bw()
print(p)


```

### Boxplots

```{r, out.width="90%"}
res<-list()
for (dataset in datasets)
{
  for (map in maper)
  {
    load(file = paste0("data/", dataset, "_", map, ".RData"))
    isexpr <- rowSums(cpm(cc) > 5) >= 2
    dane1 <- cc[isexpr,]
    klas <- unlist(read.table(file = paste0('data/', dataset, '.csv')))
    pseudoCount <- log2(dane1 + 1)
    pseudoCount <- as.data.frame(pseudoCount)
    colnames(pseudoCount) <- paste0(colnames(pseudoCount),"_",klas)
    df = melt(pseudoCount, varnames=c('Samples', 'value'))
    cos<-sub(".*bam_", "", df$variable) 
    samples<-sub("*.sorted.bam", "", df$variable) 
    df = data.frame(df, Condition = cos)
    res[[paste0(dataset,"_",map)]] <- df
  }
}

res1<-list()
for (dataset in datasets)
{
  for (map in maper)
  {
    load(file = paste0("data/", dataset, "_", map, ".RData"))
    isexpr <- rowSums(cpm(cc) > 5) >= 2
    dane1 <- cc[isexpr,]
    dane2 <- dane1[-which(rownames(dane1) %in% dziwne), ]
    klas <- unlist(read.table(file = paste0('data/', dataset, '.csv')))
    pseudoCount <- log2(dane2 + 1)
    pseudoCount <- as.data.frame(pseudoCount)
    colnames(pseudoCount) <- paste0(colnames(pseudoCount),"_",klas)
    df = melt(pseudoCount, varnames=c('Samples', 'value'))
    cos<-sub(".*bam_", "", df$variable) 
    samples<-sub("*.sorted.bam", "", df$variable) 
    df = data.frame(df, Condition = cos)
    res1[[paste0(dataset,"_",map)]] <- df
  }
}

```
```{r}
df <- res[["dataset4_star"]]
df$difficult <- "with DG"

df1 <- res1[["dataset4_star"]]
df1$difficult <- "without DG"
```

```{r}
df2 <- rbind(df, df1)
ggplot(df2, aes(x = variable, y = value, fill = difficult)) + 
  geom_boxplot() + xlab("") +
  facet_wrap(~Condition, ncol = 2, scales = "free_x") +
  ylab(expression(log[2](count + 1))) + 
  scale_fill_manual(name = "", values = c("#619CFF", "#F564E3","#5cd65c",'gold')) +
  theme(legend.position = "bottom", axis.text.x = element_blank())

```


```{r}
res<-melt(res)
colnames(res) <- c("maper", "Condition", "value", "dataset")
res$maper<-sub(".*_", "", res$dataset) 
res$dataset<-substr(res$dataset,start=1,stop=8)
res$dataset[which(res$dataset == "dataset4")] <- "GSE22260"
res$dataset[which(res$dataset == "dataset5")] <- "GSE50760"
res$dataset[which(res$dataset == "dataset6")] <- "GSE87340"
res$dataset[which(res$dataset == "dataset7")] <- "GSE42146"
res$dataset[which(res$dataset == "dataset8")] <- "GSE41364"

res1<-melt(res1)
colnames(res1) <- c("maper", "Condition", "value", "dataset")
res1$maper<-sub(".*_", "", res1$dataset) 
res1$dataset<-substr(res1$dataset,start=1,stop=8)
res1$dataset[which(res1$dataset == "dataset4")] <- "GSE22260"
res1$dataset[which(res1$dataset == "dataset5")] <- "GSE50760"
res1$dataset[which(res1$dataset == "dataset6")] <- "GSE87340"
res1$dataset[which(res1$dataset == "dataset7")] <- "GSE42146"
res1$dataset[which(res1$dataset == "dataset8")] <- "GSE41364"
```


### Wykresy gęstości 

```{r, out.width="90%"}
res$difficult <- "with DG"
res1$difficult <- "without DG"

res2 <- rbind(res, res1)
ggplot(res2, aes(x = value, fill = difficult, color = difficult)) + 
  ylim(c(0, 0.25)) +
  geom_density(alpha = 0.2) + 
  facet_grid(dataset~maper) + 
  theme(legend.position = "bottom") + 
  xlab(expression(log[2](count + 1)))


```

## Odpowiedzi dla recenzenta nr 2 linijki 18

Powtórzenie analizy bez Subreada.

### Wyszukanie trudnych genów dla dwóch mapperów

```{r, eval = F}
source("codes/google_difficult_genes_functions.R")

maper <- c("his", "sub")
for (dataset in datasets)
{
  res.dane <- list()
  klas <- unlist(read.table(file = paste0('data/', dataset, '.csv')))
  county <- NULL
  for (map in maper)
  {
    load(file = paste0("data/", dataset, "_", map, ".RData"))
    county <- cbind(county, cc)
  }
  #res.dane[["edgeR"]] <- wyszukiwarka(county1, county2, uklad = klas, method = "edgeR")
  res.dane[["edgeR"]] <- wyszukiwarka5(county, n.mapper = length(maper), design = klas, method = "edgeR")
  save(res.dane, file = paste0("results/difficult_genes5_wo_star_", dataset, ".RData"))
}

maper <- c("star", "sub")
for (dataset in datasets)
{
  res.dane <- list()
  klas <- unlist(read.table(file = paste0('data/', dataset, '.csv')))
  load(file = paste0("data/", dataset, "_", maper[1], ".RData"))
  county1 <- cc
  load(file = paste0("data/", dataset, "_", maper[2], ".RData"))
  county2 <- cc
  res.dane[["edgeR"]] <- wyszukiwarka(county1, county2, uklad = klas, method = "edgeR")
  save(res.dane, file = paste0("results/difficult_genes_wo_his_", dataset, ".RData"))
}

maper <- c("his", "sub")
for (dataset in datasets)
{
  res.dane <- list()
  klas <- unlist(read.table(file = paste0('data/', dataset, '.csv')))
  load(file = paste0("data/", dataset, "_", maper[1], ".RData"))
  county1 <- cc
  load(file = paste0("data/", dataset, "_", maper[2], ".RData"))
  county2 <- cc
  res.dane[["edgeR"]] <- wyszukiwarka(county1, county2, uklad = klas, method = "edgeR")
  save(res.dane, file = paste0("results/difficult_genes_wo_star_", dataset, ".RData"))
}
```

### Venny

oryginal

```{r venny, results="asis"}
library(VennDiagram)
library(RColorBrewer)
kolory <- brewer.pal(length(datasets), "Set1")
met <- "edgeR"

datasets1 <- c("GSE22260","GSE50760","GSE87340","GSE42146","GSE41364")
dziwne <- list()
for (dataset in datasets)
{
  load(file = paste0("results/difficult_genes_", dataset, ".RData"))
  
    dziwne[[met]][[dataset]] <- rownames(res.dane[[met]]$stats)[which(res.dane[[met]]$stats$status.group == "Sig" & res.dane[[met]]$stats$status.mappers == "Sig")]
}

nazwy <- list()
b <- get.venn.partitions(x = list(
    A=dziwne[[met]][[1]],
    B=dziwne[[met]][[2]],
    C=dziwne[[met]][[3]],
    D=dziwne[[met]][[4]],
    E=dziwne[[met]][[5]]
  ))
  a <- b$..count..
  venn.plot <- draw.quintuple.venn(
    area1 = sum(a[c(1,3,5,7,9,11,13,15,17,19,21,23,25,27,29,31)]), area2 = sum(a[c(1,2,5,6,9,10,13,14,17,18,21,22,25,26,29,30)]), 
    area3 = sum(a[c(1:4,9:12,17:20,25:28)]), area4 = sum(a[c(1:8,17:24)]), area5 = sum(a[1:16]),
    n12 = sum(a[c(1,5,9,13,17,21,25,29)]), n13 = sum(a[c(1,3,9,11,17,19,25,27)]), 
    n14 = sum(a[c(1,3,5,7,17,19,21,23)]), n15 = sum(a[c(1,3,5,7,9,11,13,15)]),
    n23 = sum(a[c(1,2,9,10,17,18,25,26)]), n24 = sum(a[c(1,2,5,6,17,18,21,22)]), 
    n25 = sum(a[c(1,2,5,6,9,10,13,14)]), n34 = sum(a[c(1:4,17:20)]), 
    n35 = sum(a[c(1:4,9:12)]), n45 = sum(a[c(1:8)]), 
    n123 = sum(a[c(1,9,17,25)]), n124 = sum(a[c(1,5,17,21)]), n125 = sum(a[c(1,5,9,13)]), 
    n134 = sum(a[c(1,3,17,19)]), n135 = sum(a[c(1,3,9,11)]), n145 = sum(a[c(1,3,5,7)]),
    n234 = sum(a[c(1,2,17,18)]), n235 = sum(a[c(1,2,9,10)]), 
    n245 = sum(a[c(1,2,5,6)]), n345 = sum(a[c(1:4)]),
    n1234 = sum(a[c(1,17)]), n1235 = sum(a[c(1,9)]),  n1245 = sum(a[c(1,5)]), 
    n1345 = sum(a[c(1,3)]), n2345 = sum(a[c(1:2)]),
    n12345 = sum(a[c(1)]),
    category = datasets1,
    fill = kolory, alpha = 0.30, cex = 1.2, fontfamily = "serif",
    rotation.degree = 360, margin = 0.1, main = "# of joint difficult genes between datasets",
    main.pos = c(0.5,0.8), height = 500,width = 500, resolution = 600, lwd = 0.5
  )
  grid.draw(venn.plot)
  grid.newpage()
  nazwy[[met]] <- b$..values..$`1`
```

bez subreada

```{r venny1, results="asis"}
library(VennDiagram)
library(RColorBrewer)
kolory <- brewer.pal(length(datasets), "Set1")
met <- "edgeR"

datasets1 <- c("GSE22260","GSE50760","GSE87340","GSE42146","GSE41364")
dziwne <- list()
for (dataset in datasets)
{
  load(file = paste0("results/difficult_genes5_wo_sub_", dataset, ".RData"))
  
    dziwne[[met]][[dataset]] <- rownames(res.dane[[met]]$stats)[which(res.dane[[met]]$stats$status.group == "Sig" & res.dane[[met]]$stats$status.mappers == "Sig")]
}

nazwy <- list()
b <- get.venn.partitions(x = list(
    A=dziwne[[met]][[1]],
    B=dziwne[[met]][[2]],
    C=dziwne[[met]][[3]],
    D=dziwne[[met]][[4]],
    E=dziwne[[met]][[5]]
  ))
  a <- b$..count..
  venn.plot <- draw.quintuple.venn(
    area1 = sum(a[c(1,3,5,7,9,11,13,15,17,19,21,23,25,27,29,31)]), area2 = sum(a[c(1,2,5,6,9,10,13,14,17,18,21,22,25,26,29,30)]), 
    area3 = sum(a[c(1:4,9:12,17:20,25:28)]), area4 = sum(a[c(1:8,17:24)]), area5 = sum(a[1:16]),
    n12 = sum(a[c(1,5,9,13,17,21,25,29)]), n13 = sum(a[c(1,3,9,11,17,19,25,27)]), 
    n14 = sum(a[c(1,3,5,7,17,19,21,23)]), n15 = sum(a[c(1,3,5,7,9,11,13,15)]),
    n23 = sum(a[c(1,2,9,10,17,18,25,26)]), n24 = sum(a[c(1,2,5,6,17,18,21,22)]), 
    n25 = sum(a[c(1,2,5,6,9,10,13,14)]), n34 = sum(a[c(1:4,17:20)]), 
    n35 = sum(a[c(1:4,9:12)]), n45 = sum(a[c(1:8)]), 
    n123 = sum(a[c(1,9,17,25)]), n124 = sum(a[c(1,5,17,21)]), n125 = sum(a[c(1,5,9,13)]), 
    n134 = sum(a[c(1,3,17,19)]), n135 = sum(a[c(1,3,9,11)]), n145 = sum(a[c(1,3,5,7)]),
    n234 = sum(a[c(1,2,17,18)]), n235 = sum(a[c(1,2,9,10)]), 
    n245 = sum(a[c(1,2,5,6)]), n345 = sum(a[c(1:4)]),
    n1234 = sum(a[c(1,17)]), n1235 = sum(a[c(1,9)]),  n1245 = sum(a[c(1,5)]), 
    n1345 = sum(a[c(1,3)]), n2345 = sum(a[c(1:2)]),
    n12345 = sum(a[c(1)]),
    category = datasets1,
    fill = kolory, alpha = 0.30, cex = 1.2, fontfamily = "serif",
    rotation.degree = 360, margin = 0.1, main = "# of joint difficult genes between datasets",
    main.pos = c(0.5,0.8), height = 500,width = 500, resolution = 600, lwd = 0.5
  )
  grid.draw(venn.plot)
  grid.newpage()
  nazwy[[met]] <- b$..values..$`1`
```

bez hisata

```{r venny2, results="asis"}
datasets1 <- c("GSE22260","GSE50760","GSE87340","GSE42146","GSE41364")
dziwne <- list()
for (dataset in datasets)
{
  load(file = paste0("results/difficult_genes5_wo_his_", dataset, ".RData"))
  
    dziwne[[met]][[dataset]] <- rownames(res.dane[[met]]$stats)[which(res.dane[[met]]$stats$status.group == "Sig" & res.dane[[met]]$stats$status.mappers == "Sig")]
}

nazwy <- list()
b <- get.venn.partitions(x = list(
    A=dziwne[[met]][[1]],
    B=dziwne[[met]][[2]],
    C=dziwne[[met]][[3]],
    D=dziwne[[met]][[4]],
    E=dziwne[[met]][[5]]
  ))
  a <- b$..count..
  venn.plot <- draw.quintuple.venn(
    area1 = sum(a[c(1,3,5,7,9,11,13,15,17,19,21,23,25,27,29,31)]), area2 = sum(a[c(1,2,5,6,9,10,13,14,17,18,21,22,25,26,29,30)]), 
    area3 = sum(a[c(1:4,9:12,17:20,25:28)]), area4 = sum(a[c(1:8,17:24)]), area5 = sum(a[1:16]),
    n12 = sum(a[c(1,5,9,13,17,21,25,29)]), n13 = sum(a[c(1,3,9,11,17,19,25,27)]), 
    n14 = sum(a[c(1,3,5,7,17,19,21,23)]), n15 = sum(a[c(1,3,5,7,9,11,13,15)]),
    n23 = sum(a[c(1,2,9,10,17,18,25,26)]), n24 = sum(a[c(1,2,5,6,17,18,21,22)]), 
    n25 = sum(a[c(1,2,5,6,9,10,13,14)]), n34 = sum(a[c(1:4,17:20)]), 
    n35 = sum(a[c(1:4,9:12)]), n45 = sum(a[c(1:8)]), 
    n123 = sum(a[c(1,9,17,25)]), n124 = sum(a[c(1,5,17,21)]), n125 = sum(a[c(1,5,9,13)]), 
    n134 = sum(a[c(1,3,17,19)]), n135 = sum(a[c(1,3,9,11)]), n145 = sum(a[c(1,3,5,7)]),
    n234 = sum(a[c(1,2,17,18)]), n235 = sum(a[c(1,2,9,10)]), 
    n245 = sum(a[c(1,2,5,6)]), n345 = sum(a[c(1:4)]),
    n1234 = sum(a[c(1,17)]), n1235 = sum(a[c(1,9)]),  n1245 = sum(a[c(1,5)]), 
    n1345 = sum(a[c(1,3)]), n2345 = sum(a[c(1:2)]),
    n12345 = sum(a[c(1)]),
    category = datasets1,
    fill = kolory, alpha = 0.30, cex = 1.2, fontfamily = "serif",
    rotation.degree = 360, margin = 0.1, main = "# of joint difficult genes between datasets",
    main.pos = c(0.5,0.8), height = 500,width = 500, resolution = 600, lwd = 0.5
  )
  grid.draw(venn.plot)
  grid.newpage()
  nazwy[[met]] <- b$..values..$`1`
```


bez stara

```{r venny3, results="asis"}
dziwne <- list()
for (dataset in datasets)
{
  load(file = paste0("results/difficult_genes5_wo_star_", dataset, ".RData"))
  
    dziwne[[met]][[dataset]] <- rownames(res.dane[[met]]$stats)[which(res.dane[[met]]$stats$status.group == "Sig" & res.dane[[met]]$stats$status.mappers == "Sig")]
}

nazwy <- list()
b <- get.venn.partitions(x = list(
    A=dziwne[[met]][[1]],
    B=dziwne[[met]][[2]],
    C=dziwne[[met]][[3]],
    D=dziwne[[met]][[4]],
    E=dziwne[[met]][[5]]
  ))
  a <- b$..count..
  venn.plot <- draw.quintuple.venn(
    area1 = sum(a[c(1,3,5,7,9,11,13,15,17,19,21,23,25,27,29,31)]), area2 = sum(a[c(1,2,5,6,9,10,13,14,17,18,21,22,25,26,29,30)]), 
    area3 = sum(a[c(1:4,9:12,17:20,25:28)]), area4 = sum(a[c(1:8,17:24)]), area5 = sum(a[1:16]),
    n12 = sum(a[c(1,5,9,13,17,21,25,29)]), n13 = sum(a[c(1,3,9,11,17,19,25,27)]), 
    n14 = sum(a[c(1,3,5,7,17,19,21,23)]), n15 = sum(a[c(1,3,5,7,9,11,13,15)]),
    n23 = sum(a[c(1,2,9,10,17,18,25,26)]), n24 = sum(a[c(1,2,5,6,17,18,21,22)]), 
    n25 = sum(a[c(1,2,5,6,9,10,13,14)]), n34 = sum(a[c(1:4,17:20)]), 
    n35 = sum(a[c(1:4,9:12)]), n45 = sum(a[c(1:8)]), 
    n123 = sum(a[c(1,9,17,25)]), n124 = sum(a[c(1,5,17,21)]), n125 = sum(a[c(1,5,9,13)]), 
    n134 = sum(a[c(1,3,17,19)]), n135 = sum(a[c(1,3,9,11)]), n145 = sum(a[c(1,3,5,7)]),
    n234 = sum(a[c(1,2,17,18)]), n235 = sum(a[c(1,2,9,10)]), 
    n245 = sum(a[c(1,2,5,6)]), n345 = sum(a[c(1:4)]),
    n1234 = sum(a[c(1,17)]), n1235 = sum(a[c(1,9)]),  n1245 = sum(a[c(1,5)]), 
    n1345 = sum(a[c(1,3)]), n2345 = sum(a[c(1:2)]),
    n12345 = sum(a[c(1)]),
    category = datasets1,
    fill = kolory, alpha = 0.30, cex = 1.2, fontfamily = "serif",
    rotation.degree = 360, margin = 0.1, main = "# of joint difficult genes between datasets",
    main.pos = c(0.5,0.8), height = 500,width = 500, resolution = 600, lwd = 0.5
  )
  grid.draw(venn.plot)
  grid.newpage()
  nazwy[[met]] <- b$..values..$`1`
```

# Geny dziwne wspólnych z Watsonem

```{r Watson, results="asis"}
Watson<-openxlsx::read.xlsx("data/geny_Watson.xlsx")

met <- "edgeR"

A=dziwne[[met]][[1]]
B=dziwne[[met]][[2]]
C=dziwne[[met]][[3]]
D=dziwne[[met]][[4]]
E=dziwne[[met]][[5]]

nasze<-intersect(E,intersect(D,intersect(C,intersect(A,B))))
wspolne<-intersect(Watson[,2],nasze)
# część wspólna ze wszystkich zestawów danych
length(wspolne)

# wspólne z poszczególnymi danymi 
wspolne <- data.frame(no.of.joint = integer(5), 
                      percent.of.ours = integer(5), 
                      percent.of.Watson = integer(5))
rownames(wspolne) <- datasets1

dane<-list()
dane[[1]]<-A
dane[[2]]<-B
dane[[3]]<-C
dane[[4]]<-D
dane[[5]]<-E

for(i in 1:5){
  wspolne[i, 1] <- length(intersect(Watson[,2], dane[[i]]))
  wspolne[i, 2] <- length(dane[[i]])
wspolne[i, 3] <- nrow(Watson)
}

knitr::kable(wspolne)


```
